### ISSUE TITLE
build fails on windows

### ISSUE THREAD

**Issue by thegtproject** [kode4food/sputter#4]
@kode4food  I would do a pull request if I knew how, but, here's the change I made to fix the issue.

```
file: cmd/sputter/repl_test.go

func TestREPLPaint(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("not valid for windows")
	}
...
```

**Comment by kode4food** [comment]
Thanks, I'll apply it!

**Comment by kode4food** [comment]
@thegtproject Committed a fix. Let me know if that works for you as I'm not often on a Windows box.

**Comment by kode4food** [comment]
@thegtproject  Just tested on windows with

```
go test ./cmd/sputter
```

Seemed to work, so I will close the issue for now.

Thanks for reporting it!

**Comment by thegtproject** [comment]
@kode4food No problem! I happened to be trying to learn about compilers/interpreters right now, and this project has been pretty valuable for me. Though I have yet to see what there is to love about the lisp syntax/style =P

**Comment by kode4food** [comment]
@thegtproject Lisp grows on you. Admittedly, it took 30 years for me, and the introduction of Clojure, but eventually you grow to appreciate it far more than other languages.

**Comment by thegtproject** [comment]
Im starting to like LISP! Been digging around sputter and starting to see how it's pretty damn cool. And described as a programmable programming language. That's just cool.

Any chance you are gonna do a write up on how sputter works? There's quite a bit in there that Im just not understanding yet.

**Comment by kode4food** [comment]
@thegtproject Sorry, I just saw this now! I will do a write-up at some point, but I'd like for the internals to stabilize a little more. I'm just starting to write the compiler now. As soon as a first cut of that's done, I'll begin a write-up.
